// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Zeytin",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Zeytin",
            targets: ["AppModule"],
            bundleIdentifier: "itkhld.dev.Zeytin",
            teamIdentifier: "Z9697UVR8J",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .leaf),
            accentColor: .presetColor(.mint),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "This app requires camera access to classify olives in real-time.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            sources: ["Views", "ViewModels", "Models", "Services"],
            resources: [
                .copy("OliveClassifier.model")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)